# Generated by Django 6.0.3 on 2026-05-28 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_usuario_token_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='empresa',
        ),
        migrations.AddField(
            model_name='ticket',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
            preserve_default=False,
        ),
    ]
