# Generated by Django 6.0.3 on 2026-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_empresa_id_alter_ticket_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('leido', 'Leido'), ('no leido', 'No leido'), ('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='no leido', max_length=20),
        ),
    ]
