# Generated by Django 6.0.3 on 2026-06-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='numero_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
