# Generated by Django 6.0.3 on 2026-06-17 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_empresa_numero_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='app.usuario'),
        ),
    ]
