# Generated by Django 6.0.3 on 2026-06-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_empresa_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='encargado',
        ),
    ]
