# Generated by Django 6.0.3 on 2026-06-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_empresa_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='encargado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='app.usuario'),
            preserve_default=False,
        ),
    ]
