# Generated by Django 6.0.3 on 2026-06-17 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_empresa_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='app.usuario'),
        ),
    ]
