# Generated by Django 6.0.3 on 2026-06-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_empresa_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_sesion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
