# Generated by Django 6.0.3 on 2026-06-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_usuario_token_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
