# Generated by Django 6.0.3 on 2026-06-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_empresa_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(max_length=20, null=True, unique=True),
        ),
    ]
