# Generated by Django 6.0.3 on 2026-06-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_empresa_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
