# Generated by Django 6.0.3 on 2026-06-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_empresa_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='telefono',
        ),
    ]
