# Generated by Django 6.0.3 on 2026-07-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_empresa_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='admin',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('encargado', 'Encargado'), ('taller', 'Taller'), ('admin', 'Admin')], default='cliente', max_length=20),
        ),
    ]
