# Generated by Django 6.0.3 on 2026-07-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_usuario_admin_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('taller', 'Taller'), ('admin', 'Admin')], default='cliente', max_length=20),
        ),
    ]
