# Generated by Django 6.0.3 on 2026-07-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_dispositivo_alter_ticket_tipo_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_tickets', to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo_tickets', to='app.dispositivo'),
        ),
    ]
