# Generated by Django 6.0.3 on 2026-07-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_ticket_idusuario_alter_ticket_tipo_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
