# Generated by Django 6.0.3 on 2026-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_empresa_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
