# Generated by Django 6.0.3 on 2026-07-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_empresa_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_sesion_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
