# Generated by Django 6.0.3 on 2026-07-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_usuario_token_sesion_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_sesion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
