# Generated by Django 6.0.3 on 2026-08-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_usuario_token_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('pendiente', 'Pendiente'), ('en progreso', 'En progreso'), ('finalizado', 'Finalizado')], default='nuevo', max_length=20),
        ),
    ]
