# Generated by Django 6.0.3 on 2026-08-05 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='app.usuario'),
        ),
    ]
