# Generated by Django 6.0.3 on 2026-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_ticket_usuario_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comentarios_taller',
            field=models.TextField(blank=True, null=True),
        ),
    ]
